---
- hosts: all
  gather_facts: True
  connection: local
  user: remote
  
  #vars:
    #- config: "/opt/creds.json" 
  
  tasks:
    - name: Gather facts about all Connection Templates
      oneview_connection_template_facts:
      #  config: "{{ config }}"
      delegate_to: localhost
